export const projects = [
  {
    title: "DICTION AI",
    description: "",
    image: "/images/previews/dictionai.webp",
    link: "https://dictionai.magnideveloper.com",
    state: "En Desarrollo",
    type: "Página Web",
  },
  {
    title: "Magni Developer",
    description: "",
    image: "/images/previews/magnideveloper.webp",
    link: "https://magnideveloper.com",
    state: "Terminado",
    type: "Página Web",
  },
  {
    title: "Calculadora",
    description: "",
    image: "/images/previews/calculator.webp",
    link: "https://calculator.magnideveloper.com",
    state: "Terminado",
    code: "https://github.com/fermeridamagni/calculator",
    type: "Página Web",
  },
  {
    title: "Generador de contraseñas",
    description: "",
    image: "/images/previews/passwordgenerator.webp",
    link: "https://passwordgenerator.magnideveloper.com",
    state: "Terminado",
    code: "https://github.com/fermeridamagni/password-generator",
    type: "Página Web",
  },
  {
    title: "Administrador de contraseñas",
    description: "",
    image: "/images/previews/default.webp",
    link: "https://passwordmanager.magnideveloper.com",
    state: "Pausado",
    type: "Página Web",
  },
  {
    title: "Laura Merida",
    description: "",
    image: "/images/previews/default.webp",
    link: "https://lauramerida.com",
    state: "Pausado",
    type: "Página Web",
  },
  {
    title: "Aedifika Grupo Inmobiliario",
    description: "",
    image: "/images/previews/default.webp",
    link: "https://aedifika.com",
    state: "Pausado",
    type: "Página Web",
  },
  {
    title: "Reloj de Tiempo",
    description: "",
    image: "/images/previews/default.webp",
    state: "En Desarrollo",
    type: "App Móvil",
  },
  {
    title: "Whatsapp Bot",
    description: "",
    image: "/images/previews/default.webp",
    state: "Pausado",
    type: "Bot",
  },
];
